# Assignment For Numpy


# Difficulty Level Beginner

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10

In [4]:
np.zeros((10) , dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [5]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [6]:
a = np.arange(10,50)
print("Original Array", a)
print(a.shape)


Original Array [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
(40,)


5. Print the type of the previous array in question 3

In [7]:
a = np.arange(10,50)
print("Original Array", a)
print(a.dtype)

Original Array [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32


6. Print the numpy version and the configuration

In [8]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/DELL/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3

In [9]:
a = np.arange(10,50)
print(a.ndim)


1


8. Create a boolean array with all the True values

In [10]:
arr = np.ones(10, dtype=bool)
print('Numpy Array: ')
print(arr)

Numpy Array: 
[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(x)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array

In [12]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], np.int32)
print(x)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


11. Reverse a vector (first element becomes last)

In [13]:
np_arr = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.flipud(np_arr))

[10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1

In [14]:
x = np.zeros((10), dtype='int32')
print(x)
print("Update sixth value to 1")
x[4] = 1
print(x)

[0 0 0 0 0 0 0 0 0 0]
Update sixth value to 1
[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [15]:
np_arr = np.identity((3), dtype='int16')
print('A 3x3 matrix:')
print(np_arr)

A 3x3 matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


14. arr = np.array([1, 2, 3, 4, 5])
    Convert the data type of the given array from int to float

In [16]:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array: ", arr)
print("Converted to Float Type: ", arr.astype('float64'))

Original Array:  [1 2 3 4 5]
Converted to Float Type:  [1. 2. 3. 4. 5.]


15. 
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

In [17]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]) 

print ("Array 1 : ", arr1) 
print ("Array 2 : ", arr2) 

output_arr = np.multiply(arr1, arr2) 
print ("Resultant Array: ", output_arr) 


Array 1 :  [[1. 2. 3.]
 [4. 5. 6.]]
Array 2 :  [[ 0.  4.  1.]
 [ 7.  2. 12.]]
Resultant Array:  [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [18]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 0.  4.  1.]
 [ 7.  2. 12.]]


17. Extract all odd numbers from arr with values(0-9)

In [19]:
array  = np.arange(10)
result = []
for i in array:
    if i%2 != 0:
        result.append(i)
    print("The Odd Numbers extracted are: ", np.array(result))

The Odd Numbers extracted are:  []
The Odd Numbers extracted are:  [1]
The Odd Numbers extracted are:  [1]
The Odd Numbers extracted are:  [1 3]
The Odd Numbers extracted are:  [1 3]
The Odd Numbers extracted are:  [1 3 5]
The Odd Numbers extracted are:  [1 3 5]
The Odd Numbers extracted are:  [1 3 5 7]
The Odd Numbers extracted are:  [1 3 5 7]
The Odd Numbers extracted are:  [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [20]:
array  = np.arange(10)
result = []
for i in array:
    if i%2 != 0:
        result.append(i)
print("The Odd Numbers extracted are: ", np.array(result))
print("Odd Numbers converted to -1 are: ", np.where(result==result, -1, result ))

The Odd Numbers extracted are:  [1 3 5 7 9]
Odd Numbers converted to -1 are:  [-1 -1 -1 -1 -1]


19. arr = np.arange(10)
    Replace the values of indexes 5,6,7 and 8 to 12

In [21]:
arr = np.arange(10)
print("Original Array is: ", arr)
print("Replaced Array is: ") 
arr[5:9] = 12
print(arr)


Original Array is:  [0 1 2 3 4 5 6 7 8 9]
Replaced Array is: 
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [22]:
my_arr = np.ones((5,5), dtype='int32')
print("Original Array:")
print(my_arr)
print("1 on the border and 0 inside in the array")
my_arr[1:-1,1:-1] = 0
print(my_arr)

Original Array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on the border and 0 inside in the array
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


21. arr2d = np.array([[1, 2, 3],
                      [4, 5, 6], 
                     [7, 8, 9]])
    Replace the value 5 to 1

In [23]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array: ", arr2d)
print("Replaced Array 5 with 1: ")
arr2d.flat[4] = 1 
print(arr2d)


Original Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Replaced Array 5 with 1: 
[[1 2 3]
 [4 1 6]
 [7 8 9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
    Convert all the values of 1st array to 64

In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.flat[0:3] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [25]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], np.int32)
print(x)
a = x[0]
print("The first 1D Elements are: ", a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
The first 1D Elements are:  [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], np.int32)
print(" The 2nd value from 2nd 1-D array is:", x[1][1])


 The 2nd value from 2nd 1-D array is: 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [27]:
arr = np.arange(9).reshape(3, 3)
arr3 = arr[0:-1, -1]

arr3

array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:

arr = np.arange(100).reshape(10, 10)
maxInColumns = np.amax(arr, axis=1)
val = max(maxInColumns)
val

99

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])¶
Find the common items between a and b

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [33]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where(name[data] != "Will"))

[2 3]
(array([1], dtype=int64),)


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [34]:
import random

name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
data = np.random.randint(7, size=random.randrange(1, 10))
print(data)
print(np.where((name[data] != "Joe") & (name[data] != "Will")))

[0 1 2 0 3 0 6 4 5]
(array([0, 3, 4, 5], dtype=int64),)


31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [35]:
arr = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr

array([[ 7.7667133 , 14.84422432,  4.78489951],
       [ 2.98757795,  6.74544709,  4.1961382 ],
       [ 9.52095824,  5.45529116,  6.73108655],
       [ 6.63658272, 11.39965214,  2.00923177],
       [ 3.07317646, 11.72962197, 11.63473446]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [36]:
arr = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))

33. Swap axes of the array you created in Question 32

In [37]:
np.swapaxes(arr, 0, 1)
arr

array([[[11.22320717, 10.22335779, 13.11392439, 14.81559985],
        [ 2.36410667, 12.39550051,  8.31588374,  9.23326303]],

       [[13.89196422,  2.09433095, 15.06370908,  1.15536464],
        [ 9.7004548 ,  9.60107675,  7.95998966, 14.03195463]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [38]:
import math

arr = np.arange(10)
print(arr)
new_arr = filter(lambda x: x if math.sqrt(x) > 0.5 else 0, arr)
np.asarray(list(new_arr))

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [39]:
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)

[7 3 5 7 6 8]
[ 4  2 11  7  2  7]


(array([3], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
val = np.intersect1d(a, b)

a = filter(lambda x: x if x not in val else None, a)
np.asarray(list(a))

array([1, 2, 3, 4])

38. Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

In [42]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray[:, 1] = 10
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [43]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [44]:
matrix = np.random.randint(20, size=(random.randint(0, 5), random.randint(0, 5)))
np.cumsum(matrix)

array([], dtype=int32)